package ru.pharus.socnetwork.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.validator.constraints.NotBlank;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Past;
import java.time.LocalDateTime;

/**
 * Class Message java Bean entity - used for chat messages with users
 *
 * Lombok knowledge, for example:
 * Getters and Setters, Equals and Hashcode methods
 * are generated by Lombok annotations
 */

@Data
@AllArgsConstructor
@NoArgsConstructor
public class Message implements Comparable<Message> {
    //id INT AUTO_INCREMENT PRIMARY KEY,
    private int id;
    // from_user_id   INT NOT NULL DEFAULT '0',
    @NotNull
    private int fromUserId;
    //to_user_id   INT NOT NULL DEFAULT '0',
    @NotNull
    private int toUserId;
    //message TEXT,
    @NotBlank (message = "Enter message")
    private String message;
    //post_time DATETIME,
    @Past
    private LocalDateTime postTime;

    @Override
    public int compareTo(Message o) {
        // Пока решил использовать в качестве естественного порядка сортировки только id
        return (id < o.id) ? -1 : (id > o.id) ? 1 : 0;
    }
}
