package ru.pharus.socnetwork.entity;


/**
 *
 * For example:
 * Getters and Setters, Equals and Hashcode methods
 * are generated by IntelliJ IDEA
 */

public class Vendor {
    private int id;
    private String name;

    public int getId(){
        return id;
    }
    public void setID(int id){
        this.id = id;
    }

    public String getName(){
        return name;
    }
    public void setName(String name){
        this.name = name;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Vendor vendor = (Vendor) o;

        if (id != vendor.id) return false;
        return name.equals(vendor.name);
    }

    @Override
    public int hashCode() {
        int result = id;
        result = 31 * result + name.hashCode();
        return result;
    }
}
